version: "3.9"
services:
    db:
        container_name: cve-db
        image: "mongo"
        ports:
            - "27017-27019"
    front:
        container_name: cve-front
        build:
            context: ./front-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
            - back
        ports: 
            - "3000:3000"
        environment:
            REACT_APP_BACKEND_HOST: "${CVE_WATCH_BACKEND_URL}:8080"
    back:
        container_name: cve-back
        build:
            context: ./back-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
        ports: 
            - "8080:8080"
        environment:
            MONGODB_URI: mongodb://cve-db:27017
            FRONT_END_HOST: "${CVE_WATCH_FRONTEND_URL}:3000"
            NODE_APP_ENV: "production"
            PORT: 8080
            GITHUB_AUTH_TOKEN: "test"
    