version: "3.9"
services:
    db:
        container_name: cve-db
        image: "mongo"
        ports:
            - "27017-27019"
    front:
        container_name: cve-front
        build:
            context: ./front-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
            - back
        ports: 
            - "80:80"
        environment:
            REACT_APP_BACKEND_HOST: "${CVE_WATCH_BACKEND_URL}"
    back:
        container_name: cve-back
        build:
            context: ./back-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
        ports: 
            - "80:80"
        environment:
            MONGODB_URI: ${CVE_WATCH_DB_URI}
            FRONT_END_HOST: "${CVE_WATCH_FRONTEND_URL}"
            NODE_APP_ENV: "production"
            PORT: 80
            GITHUB_AUTH_TOKEN: "test"
    
