version: "3.9"
services:
    db:
        container_name: cve-db
        image: "mongo"
        ports:
            - "27017-27019"
    front:
        container_name: cve-front
        build:
            context: ./front-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
            - back
        ports: 
            - "80:80"
    back:
        container_name: cve-back
        build:
            context: ./back-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
        ports: 
            - "8080:8080"
        environment:
            MONGODB_URI: "mongodb://cve-db:27017"
            NODE_APP_FRONTEND_BASE_URL: "http://localhost:80" #The hostname of the frontend
            REACT_APP_BACKEND_BASE_URL: "http://localhost:8080" #The hostname of the backend 
            NODE_APP_ENV: "development" #Determines whether real data is provided and whether secure cookies are used.
            NODE_APP_PORT: 8080
            GITHUB_AUTH_TOKEN: "test" #Replace this token with a valid GitHub API token
    
