version: "3.9"
services:
    front:
        build:
            context: ./front-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
            - back
        ports: 
            - "3000"
        environment:
            REACT_APP_BACKEND_HOST: back
    back:
        build:
            context: ./back-end/
            dockerfile: ./Dockerfile
        depends_on:
            - db
        ports: 
            - "8080"
        environment:
            MONGODB_URI: db
    db:
        image: "mongo"
        ports:
            - "27017-27019"
