version: "3.9"
services:
    db:
        container_name: cve-db
        image: "cvewatchcr.azurecr.io/mongo:latest"
        ports:
            - "27017-27019"
    front:
        container_name: cve-front
        image: "cvewatchcr.azurecr.io/cvewatch_front:latest"
        depends_on:
            - back
        ports: 
            - "3000:3000"
        environment:
            REACT_APP_BACKEND_HOST: "${CVE_WATCH_BACKEND_URL}:8080"
    back:
        container_name: cve-back
        image: "cvewatchcr.azurecr.io/cvewatch_back:latest"
        depends_on:
            - db
        ports: 
            - "8080:8080"
        environment:
            MONGODB_URI: mongodb://cve-db:27017
            FRONT_END_HOST: "${CVE_WATCH_FRONTEND_URL}:3000"
            NODE_APP_ENV: "production"
            PORT: 8080