name: $(BuildID)

variables:
  - name: working-dir
    value: 'front-end/'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'front-end/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  workingDirectory: $(working-dir)